volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  monitoring_network:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: postgres-spring-boot-actuator-studies
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: springBootActuatorStudies_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - monitoring_network

  api:
    build: .
    container_name: spring-boot-actuator-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/springBootActuatorStudies_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres1234
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring_network