global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "products-api-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api:8080"]
        labels:
          application: "product-api"